---
apiVersion: v1
kind: Service
metadata:
  name: carts
  labels:
    name: carts
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: http
    targetPort: {{ .Values.carts.containerPort }}
  selector:
    name: carts
