apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalogue
  labels:
    name: catalogue
    release: mkdev-wob-101
spec:
  namespaceSelector:
    matchNames:
    - socks-shop
  selector:
    matchLabels:
      name: catalogue
  endpoints:
  - port: http
