apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: front-end
  labels:
    name: front-end
    release: mkdev-wob-101
spec:
  namespaceSelector:
    matchNames:
    - socks-shop
  selector:
    matchLabels:
      name: front-end
  endpoints:
  - port: http
