apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders
  labels:
    name: orders
    release: mkdev-wob-101
spec:
  namespaceSelector:
    matchNames:
    - socks-shop
  selector:
    matchLabels:
      name: orders
  endpoints:
  - port: http
