---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    name: orders
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: http
    targetPort: {{ .Values.orders.containerPort }}
  selector:
    name: orders
