---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    name: shipping
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    name: http
    targetPort: {{ .Values.shipping.containerPort }}
  selector:
    name: shipping
